# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.cache/wt [current_project]
set_property parent.project_path C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/Control_visualizador_dinamico_8digitos_7seg.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/D_flip_flop.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/Generador_CE_1KHz.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/Registro_PUL.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/bbfifo_16x8.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/codificador_con_prioridad_2_a_1.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/decodificador_1_a_2.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/detector_flancos.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/generador_baudios.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/gestion_2_interrupciones.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/imports/Downloads/kcpsm3.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/kcuart_rx.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/kcuart_tx.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/or_2_bits.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/picoblaze3_empotrado_s7.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/imports/sw/picocode_s7.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/rs_flip_flop.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/selec_16_entradas_con_reg_y_bypass.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/selec_16_salidas_con_reg_y_mem_esc_lec.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/temporizador.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/uart_rs232.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/uart_rx.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/uart_tx.vhd
  C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/sources_1/new/top_ejemplo_basico_picoblaze_3_Nexys_4DDR.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ndres/Desktop/Teleco/3/1cuatri/CEP/PRACTICAS/Practica3/Practica3_1/Practica3_1.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_ejemplo_basico_picoblaze_3_Nexys_4DDR -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_ejemplo_basico_picoblaze_3_Nexys_4DDR.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_ejemplo_basico_picoblaze_3_Nexys_4DDR_utilization_synth.rpt -pb top_ejemplo_basico_picoblaze_3_Nexys_4DDR_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
